---
- hosts: "127.0.0.1"
- hosts: "all"

## 初始化节点
- hosts: "{{ host_groups }}"
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'init' }

## 生成ssh认证key
- hosts: 127.0.0.1
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'ssh-key' }

# 创建rke工作用户
- hosts: "{{ host_groups }}"
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'rke-user' }

# 安装rke k8s集群
- hosts: 127.0.0.1
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'rke-k8s' }

# 节点 kubectl 配置
- hosts: "{{ host_groups }}"
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'kubectl' }

# rancher 创建 rke 导入集群并获取导入命令
- hosts: 127.0.0.1
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'rke-k8s-cfg' }

# 导入rke k8s集群
- hosts: 127.0.0.1
  vars_files:
    - /etc/ansible/config/all.yaml
  gather_facts: false
  roles:
  - { role: 'rke-k8s' }

# todo
# 安装Haproxy
#- hosts: "{{ host_groups }}"
#  gather_facts: true
#  roles:
#  - { role: 'haproxy' }

# 安装Keepalived
#- hosts: "{{ host_groups }}"
#  gather_facts: true
#  roles:
#  - { role: 'keepalived' }