---    
# 节点初始化
- name: 创建ssh工作目录
  file: 
    path: " /etc/ansible/cluster/{{ host_group }}/ssh/ "
    state: directory

- name: 生成ssh key文件
  shell: " cd /etc/ansible/cluster/{{ host_group }}/ssh/; {{ item }} "
  with_items:
    - ' ssh-keygen -q -t rsa -f ssh_rsa_key -C "" -N "" '

